### ISSUE TITLE
pdftexcmd: Checksum Computation

### ISSUE THREAD

**Issue by manuel-kuehner** [ho-tex/oberdiek#34]
It's about the checksum computation in pdftexcmd that is apparently different for LaTeX and LuaTeX as reported in https://tex.stackexchange.com/questions/219199.

I am not an expert - I only "suffer" from the problem that seems to be a couple of years old now.

The problem seems to be Windows specific.

**Comment by agrahn** [comment]
Bellow, there is a simple test file (with zero pages output).

Run `pdflatex` and `lulatex` on it. It writes the MD5 checksum of the test file to the terminal and into the log file. The checksums should be the same for pdfLaTeX and for LuaLaTeX and be equal to the output uf the `md5sum` Unix command.

On Windows platform the checksum calculated by LuaLaTeX is wrong, because in file `texmf-dist/scripts/oberdiek/pdftexcmds.lua`, the files are opened in text mode. They should rather be opened in binary mode. The suggested patch in https://tex.stackexchange.com/a/222272 fixes this for all platforms.

Test file:

````latex
\documentclass{article}

\usepackage{pdftexcmds}

\begin{document}

\makeatletter
\typeout{++++++++++++++ md5checksum ++++++++++++++}
\typeout{\pdf@filemdfivesum{\jobname.tex}}
\typeout{++++++++++++++ md5checksum ++++++++++++++}
\makeatother

\end{document}

**Comment by davidcarlisle** [comment]
yes thanks I've made the change locally, not committed yet as the build
fails elsewhere in the bundle unrelated to this package (documentation
failing with a biblatex change) I'll commit and push to github once that is
resolved. thanks for identifying the issue here.

**Comment by agrahn** [comment]
Wow, this was really fast. Thank you, David!

**Comment by manuel-kuehner** [comment]
Copy and Paste: Wow, this was really fast. Thank you, David!

**Comment by davidcarlisle** [comment]
this is now on ctan, thanks for the report.
