### ISSUE TITLE
[pmboxdraw] [DOC] possible space problems at start of 1 User interface

### ISSUE THREAD

**Issue by jfbu** [ho-tex/oberdiek#54]
Here is a screenshot:

![capture d ecran 2018-12-13 a 17 17 47](https://user-images.githubusercontent.com/2589111/49951880-443e9a80-fefb-11e8-9e41-2b5a876394c8.png)

I wonder if this is intended design or perhaps for some reason `P M B O X D R A W` takes more space horizontally than in original. I see the PDF is obtained via "LuaTeX-1.7.0". I suspect original used pdfLaTeX and this could be related to this issue. Due to the problem with the line with the date, I suspect something having to do with spaces, for mono font (I did not at all look up the source).

**Comment by davidcarlisle** [comment]
oops the documentation is being set with a config that uses lmvtt (variable typewriter) for tt (I'm not sure that's a good plan)

we could use

 `% \fontfamily{lmtt}\selectfont`

instead of

   `% \ttfamily`

In the source of that example, but it may be better to globally set the default tt font back to fixed width lmtt

**Comment by davidcarlisle** [comment]
fixed (with local setting) at commit
caeef7256f9fc7e3e2e30a6895243552fb1ab4b4
